[versions]

kotlin = "1.9.23"
ksmt = "0.5.8"

[libraries]

ksmt-core = { module = "io.ksmt:ksmt-core", version.ref = "ksmt" }
ksmt-z3 = { module = "io.ksmt:ksmt-z3", version.ref = "ksmt" }
ksmt-runner = { module = "io.ksmt:ksmt-runner", version.ref = "ksmt" }

[plugins]
